### ISSUE TITLE
The uploaded malicious plug-in is parsed and the command is executed

### ISSUE THREAD

**Issue by afeng2016-s** [perfree/PerfreeBlog#15]
## Vulnerability information
PerfreeBlog implements the extension plug-in function based on SpringBoot and pf4j. After the plug-in is developed, it is packaged as a jar package, which can be directly installed and used online through the plug-in management of PerfreeBlog background. If an attacker develops a plug-in and inserts malicious code, uploading the malicious plug-in after the malicious code is parsed can trigger command execution.

## affected version
<= v3.1.2

## vulnerability analysis
1. Download the latest PerfreeBlog running package and decompress it.
After the directory is decompressed, run start.bat
![image](https://github.com/perfree/PerfreeBlog/assets/85676107/7987acdc-e2af-49dd-8f30-0a2d6772f9d9)

2, Access the Web service, initialize the database and administrator account.
![image](https://github.com/perfree/PerfreeBlog/assets/85676107/bbc7f4c4-92a1-4f16-aff5-69b9883c1cb5)

3. Make a plug-in with malicious code.
Plug-in development refer to: https://perfree.gitee.io/plugin-develop/create.html.
The malicious code is as follows: the calculator pops up when admin/plugin/access/list is accessed.
![image](https://github.com/perfree/PerfreeBlog/assets/85676107/598830a1-b5f7-41ad-a24b-330b980c6cfc)

4. Upload the plug-in and run.
![image](https://github.com/perfree/PerfreeBlog/assets/85676107/66598ce1-d629-44b6-b202-51292a38964f)

![image](https://github.com/perfree/PerfreeBlog/assets/85676107/b1a015a1-b1e4-4741-ad4f-a03908ab3370)

5. access the admin/plugin/access/list interface and execute the malicious code successfully.
![image](https://github.com/perfree/PerfreeBlog/assets/85676107/84eed585-8b79-4c59-a416-60564cd81192)

**Comment by attritionorg** [comment]
"_it is packaged as a jar package, which can be directly installed and used online through the plug-in management of PerfreeBlog background_"

So how is this a vulnerability? It requires admin access to then use intended functionality. It's a trusted interface, so if an admin wants to run arbitrary code, there is likely other ways to do that which are intended as well, no?
