### ISSUE TITLE
升完级出现了空指针异常

### ISSUE THREAD

**Issue by lei-cheung** [perfree/PerfreeBlog#3]
<img width="1406" alt="图片" src="https://user-images.githubusercontent.com/77766387/146896142-fd0cabf2-0769-4655-914f-87f7884c2a88.png">

**Comment by perfree** [comment]
看报错是某篇文章没有读取到创建时间，但是发表文章的话创建时间肯定会有的，能描述下当前是什么环境吗？比如mysql数据库

**Comment by lei-cheung** [comment]
sqlite

**Comment by perfree** [comment]
感谢反馈~已验证该问题，稍后会临时更新一个版本解决

**Comment by lei-cheung** [comment]
你给一个邮箱，我把我这边的包包给你发邮件

**Comment by perfree** [comment]
您可以在resources目录下新建update-sqlite.sql，如果已经有的话，可以直接在文件里边追加如下代码
`UPDATE "main"."p_article" set slug = id where slug is null;`并将配置文件config/application.yml中将version修改为2.0.0，之后启动项目即可
