### ISSUE TITLE
首页微信群 `二维码` 过期

### ISSUE THREAD

**Issue by lei-cheung** [perfree/PerfreeBlog#4]
README.md 首页 微信群 `二维码` 过期

**Comment by perfree** [comment]
明天会更新下，可以先加我微信拉进群里
![2AA9C820-052C-4494-A0BA-03978D3F615E](https://user-images.githubusercontent.com/34746579/146906211-a9c4d649-13e2-4ac9-b396-eb0fccde0c15.jpeg)
